config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: 'users/passwords'
  }


   devise_for :admin,skip:[:registrations,:passwords],controllers: {
    sessions: "admin/sessions"
  }


  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
   end

  get "search" => "searches#search"

  scope module:'public' do
    get 'users/unsubscribe'
    get 'users/withdraw'
    resources:users,only:[:index,:show,:edit,:update] do
      member do
        get :favorites
      end
    end
  end
  scope module:'public' do
    resources:dictionaries do
      resource :favorites
      resources:comments,only:[:create,:index,:destroy]
      resources:details do
      patch 'counter'
      end
    end
  end

  namespace :admin do
    resources:users,only:[:index,:show,:edit,:update]
  end

  namespace :admin do
    resources:comments,only:[:index,:show,:destroy]
  end

  namespace :admin do
    get '/' => 'homes#top',as: :homes
  end

  scope module:'public' do
    root to:'homes#top'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to:user
  belongs_to:dictionary
  
  validates :comment_contents,presence:true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!, except: [:top]
  def index
    @comments = Comment.all
  end

  def show
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/comments/index.html.erb
<div class="container-fluid max-container">
  <div class="row">
    <h1 class="col-md-12 text-center">コメント一覧</h1>
    <div class="col-md-12">
      <table>
        <thead>
          <tr>
            <th>コメント者</th>
            <th>コメント</th>
            <th>コメント日時</th>
            <th></th>
          </tr>
        </thead>
        <% @comments.each do |comment| %>
        <tbody>
          <tr>
            <td>
              <%= comment.user.last_name %><%= comment.user.first_name %>
            </td>
            <td>
              <%= comment.comment_contents %>
            </td>
            <td>
              <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            </td>
            <td>
              <%= link_to "削除",admin_comment_path(comment.id),method: :delete,"data-confirm"=>"本当にさくじょしますか？"  %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/comments/show.html.erb
<h1>Admin::Comments#show</h1>
<p>Find me in app/views/admin/comments/show.html.erb</p>