config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: 'users/passwords'
  }


   devise_for :admin,skip:[:registrations,:passwords],controllers: {
    sessions: "admin/sessions"
  }


  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
   end

  get "search" => "searches#search"

  scope module:'public' do
    get 'users/unsubscribe'
    get 'users/withdraw'
    resources:users,only:[:index,:show,:edit,:update] do
      member do
        get :favorites
      end
    end
  end
  scope module:'public' do
    resources:dictionaries do
      resource :favorites
      resources:comments,only:[:create,:index,:destroy]
      resources:details do
      patch 'counter'
      end
    end
  end

  namespace :admin do
    resources:users,only:[:index,:show,:edit,:update]
  end

  namespace :admin do
    resources:comments,only:[:index,:show,:destroy]
  end

  namespace :admin do
    get '/' => 'homes#top',as: :homes
  end

  scope module:'public' do
    root to:'homes#top'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @dictionaries = Dictionary.opening.looks(params[:word])
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class="container-fluid max-container">
  <div class="row">
    <h2 class="col-md-12">検索</h2>
    <div claa="col-md-12 text-center">
      <table class="table table-hover table-inverse">
      <tbody>
        <% @dictionaries.each do |dictionary| %>
          <tr>
            <td>
              <%= link_to dictionary_path(dictionary.id) do %>
                <%= dictionary.title %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>