config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: 'users/passwords'
  }


   devise_for :admin,skip:[:registrations,:passwords],controllers: {
    sessions: "admin/sessions"
  }


  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
   end

  get "search" => "searches#search"

  scope module:'public' do
    get 'users/unsubscribe'
    get 'users/withdraw'
    resources:users,only:[:index,:show,:edit,:update] do
      member do
        get :favorites
      end
    end
  end
  scope module:'public' do
    resources:dictionaries do
      resource :favorites
      resources:comments,only:[:create,:index,:destroy]
      resources:details do
      patch 'counter'
      end
    end
  end

  namespace :admin do
    resources:users,only:[:index,:show,:edit,:update]
  end

  namespace :admin do
    resources:comments,only:[:index,:show,:destroy]
  end

  namespace :admin do
    get '/' => 'homes#top',as: :homes
  end

  scope module:'public' do
    root to:'homes#top'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:dictionaries,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:comments,dependent: :destroy

  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true
  validates :first_name_kana,presence:true
  validates :email,presence:true
  validates :telephone_number,presence:true
  validates :postal_code,presence:true
  validates :address,presence:true
  validates :encrypted_password,presence:true

  def favorite_user_dictionary
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:dictionary_id)
    @favorite_dictionaries = Dictionary.find(favorites)
  end


  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
   find_or_create_by!(email: 'guest@example.com',
                      last_name:"ゲスト",
                      first_name: "ユーザー",
                      last_name_kana: "げすと",
                      first_name_kana:"ゆーざー",
                      postal_code:"123456",
                      address:"北海道",
                      telephone_number:"12345678910",
                      is_deleted:"false"
                      ) do |user|
     user.password = SecureRandom.urlsafe_base64
   end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:top]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:telephone_number,:address,:postal_code,:is_deleted,:production)
  end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ユーザープロフィール編集</h1>
<%= form_with model:@user,url:admin_user_path(@user.id),method: :patch,local:true do |user| %>
  <p>名前</p><%= user.text_field:last_name,placeholder:"田中" %><%= user.text_field:first_name,placeholder:"太郎" %>
  <p>ふりがな</p><%= user.text_field:last_name_kana,placeholder:"タナカ" %><%= user.text_field:userirst_name_kana,placeholder:"タロウ" %>
  <p>自己紹介</p><%= user.text_area:production,placeholder:"自己紹介文を書いてみましょう(この欄は空白でも問題ありません)。" %>
  <p>メールアドレス</p><%= user.text_field:email,placeholder:"tanaka@tarou.com" %>
  <p>電話番号(ハイフンなし)</p><%= user.text_field:telephone_number,placeholder:"00000000000" %>
  <p>郵便番号(ハイフンなし)</p><%= user.text_field:postal_code,placeholder:"0000000" %>
  <p>住所</p><%= user.text_field:address,placeholder:"東京都渋谷区神山町〇-〇" %>
  <p>退会ステータス</p>
  <%= user.radio_button:is_deleted, :false %>
  <%= user.label:is_deleted, :"有効" %>
  <%= user.radio_button:is_deleted, :true %>
  <%= user.label:is_deleted, :"退会" %>
  <%= user.submit "変更を保存",class:"btn btn-sm btn-success" %>
<% end %>

app/views/admin/users/index.html.erb
<div class="container-fluid max-container">
   <div class="row">
      <h1 class="col-md-12 text-center">ユーザー一覧</h1>
      <div class="col-md-12">
            <table border="5" class="mx-auto">
               <thead>
                  <tr>
                     <th>ユーザーID</th>
                     <th>ユーザー名(ふりがな)</th>
                     <th>メールアドレス</th>
                     <th>退会ステータス</th>
                     <th>投稿日時</th>
                  </tr>
               </thead>
               <% @users.each do |user| %>
               <tbody>
                  <tr>
                     <td><%= user.id %></td>
                     <td>
                        <%= link_to admin_user_path(user.id) do %>
                          <%= user.last_name %>
                          <%= user.first_name %>
                          (<%= user.last_name_kana %>
                          <%= user.first_name_kana %>)
                        <% end %>
                     </td>
                     <td><%= user.email %></td>
                     <td>
                        <% if user.is_deleted == false %>
                          <%= "有効" %>
                        <% else %>
                          <%= "退会" %>
                        <% end %>
                     </td>
                     <td><%= user.created_at.strftime("%Y/%m/%d") %></td>
                  </tr>
               </tbody>
               <% end %>
            </table>
      </div>
   </div>
</div>
<h1>ユーザー一覧</h1>

app/views/admin/users/show.html.erb
<h1>ユーザープロフィール</h1>
<p>名前</p><%= @user.last_name %><%= @user.first_name %>
<p>ふりがな</p><%= @user.last_name_kana %><%= @user.first_name_kana %>
<p>自己紹介</p><%= @user.production %>
<p>メールアドレス</p><%= @user.email %>
<p>電話番号</p><%= @user.telephone_number %>
<p>郵便番号</p><%= @user.postal_code %>
<p>住所</p><%= @user.address %>
<%= link_to "プロフィールを編集",edit_admin_user_path(@user.id),method: :get,class:"btn btn-sm btn-success" %>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>