config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: 'users/passwords'
  }


   devise_for :admin,skip:[:registrations,:passwords],controllers: {
    sessions: "admin/sessions"
  }


  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
   end

  get "search" => "searches#search"

  scope module:'public' do
    get 'users/unsubscribe'
    get 'users/withdraw'
    resources:users,only:[:index,:show,:edit,:update] do
      member do
        get :favorites
      end
    end
  end
  scope module:'public' do
    resources:dictionaries do
      resource :favorites
      resources:comments,only:[:create,:index,:destroy]
      resources:details do
      patch 'counter'
      end
    end
  end

  namespace :admin do
    resources:users,only:[:index,:show,:edit,:update]
  end

  namespace :admin do
    resources:comments,only:[:index,:show,:destroy]
  end

  namespace :admin do
    get '/' => 'homes#top',as: :homes
  end

  scope module:'public' do
    root to:'homes#top'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to:user
  belongs_to:dictionary
  
  validates :comment_contents,presence:true
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to:dictionary
  has_many:keys,dependent: :destroy

  validates :word,presence:true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  has_one_attached:image
  belongs_to:user
  has_many:favorites,dependent: :destroy
  has_many:comments,dependent: :destroy
  has_many:tag_posts,dependent: :destroy
  has_many:tags,through: :tag_posts,dependent: :destroy
  has_many:details,dependent: :destroy

  enum post_status: {closing:0,opening:1}
  
  validates :title,presence:true
  validates :summery,presence:true
  validates :post_status,presence:true

  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height])
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name:old)
    end
    new_tags.each do |new|
      new_dictionary_tag = Tag.find_or_create_by(tag_name:new)
      self.tags << new_dictionary_tag
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id:user.id)
  end

  def self.looks(word)
      @dictionary = Dictionary.where("title LIKE?","%#{word}%")
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :dictionary
end

app/models/key.rb
class Key < ApplicationRecord
  belongs_to:detail
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many:tag_posts,dependent: :destroy,foreign_key:'tag_id'
  has_many:dictionaries,through: :tag_posts,dependent: :destroy

  validates:tag_name,uniqueness:true,presence:true
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
  belongs_to:dictionary
  belongs_to:tag

  validates:dictionary_id,presence:true
  validates:tag_id,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:dictionaries,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:comments,dependent: :destroy

  validates :last_name,presence:true
  validates :first_name,presence:true
  validates :last_name_kana,presence:true
  validates :first_name_kana,presence:true
  validates :email,presence:true
  validates :telephone_number,presence:true
  validates :postal_code,presence:true
  validates :address,presence:true
  validates :encrypted_password,presence:true

  def favorite_user_dictionary
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:dictionary_id)
    @favorite_dictionaries = Dictionary.find(favorites)
  end


  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
   find_or_create_by!(email: 'guest@example.com',
                      last_name:"ゲスト",
                      first_name: "ユーザー",
                      last_name_kana: "げすと",
                      first_name_kana:"ゆーざー",
                      postal_code:"123456",
                      address:"北海道",
                      telephone_number:"12345678910",
                      is_deleted:"false"
                      ) do |user|
     user.password = SecureRandom.urlsafe_base64
   end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:top]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:telephone_number,:address,:postal_code,:is_deleted,:production)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_homes_path
    else
        root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
        root_path
    elsif resource_or_scope == :admin
        admin_homes_path
    else
        root_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:production,:postal_code,:address,:telephone_number])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @dictionaries = Dictionary.opening.looks(params[:word])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word,placeholder:"辞書を検索" %>
      <%= f.submit "検索",class:"btn btn-sm btn-success" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyDictionary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/3fdee408bb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
       <nav class="navbar navbar-expand-lg navbar-light">
          <%= link_to "<<戻る", :back %>
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <div class="search-box">
                <%= render partial:"layouts/search" %>
              </div>
              <% if request.fullpath.include? "/admin" %>
                <% if admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to admin_users_path,method: :get,class:"nav-link" do %>
                      <span class="fa-sharp fa-solid fa-users fa-2x header-icon"></span><p class="header-font">ユーザー一覧</p>
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to admin_comments_path,method: :get,class:"nav-link" do %>
                      <span class="fa-solid fa-comments fa-2x header-icon"></span><p class="header-font">コメント一覧</p>
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to destroy_admin_session_path,method: :delete,class:"nav-link" do %>
                      <span class="fa-solid fa-right-from-bracket fa-2x header-icon"></span><p class="header-font">ログアウト</p>
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to new_admin_session_path,method: :get,class:"nav-link" do %>
                      <span class="fa-solid fa-right-to-bracket fa-2x header-icon"></span><p class="header-font">ログイン</p>
                    <% end %>
                  </li>
                <% end %>
              <% elsif user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id),method: :get,class:"nav-link" do %>
                    <span class="fa-solid fa-user fa-2x header-icon"></span><p class="header-font">プロフィール</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to dictionaries_path,method: :get,class:"nav-link" do %>
                    <span class="fa-solid fa-book fa-2x header-icon"></span><p class="header-font">辞書一覧</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_dictionary_path,method: :get,class:"nav-link" do %>
                    <span class="fa-solid fa-book-medical fa-2x header-icon"></span><p class="header-font">辞書作成</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path,method: :delete,class:"nav-link" do %>
                    <span class="fa-solid fa-right-from-bracket fa-2x header-icon"></span><p class="header-font">ログアウト</p>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to new_user_registration_path,method: :get,class:"nav-link" do %>
                    <span class="fa-solid fa-user-plus fa-2x header-icon"></span><p class="header-font">新規登録</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path,method: :get,class:"nav-link" do %>
                    <span class="fa-solid fa-right-to-bracket fa-2x header-icon"></span><p class="header-font">ログイン</p>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <footer>

    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>